// <auto-generated />
using CourseWorksPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseWorksPortal.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190908225200_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("CourseWorksPortal.Models.CourseWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("File");

                    b.Property<string>("File_name");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CourseWorks");
                });

            modelBuilder.Entity("CourseWorksPortal.Models.FavoriteWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseWork_Id");

                    b.Property<int>("Username_Id");

                    b.HasKey("Id");

                    b.ToTable("FavoriteWorks");
                });

            modelBuilder.Entity("CourseWorksPortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
